# Dockerfile.graph-node
FROM rust:1.70-slim-bullseye AS builder
RUN apt-get update && apt-get install -y \
    cmake pkg-config libssl-dev libpq-dev git clang protobuf-compiler

RUN git clone https://github.com/graphprotocol/graph-node /graph-node
WORKDIR /graph-node
RUN cargo build --release

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y libssl-dev ca-certificates libpq5
COPY --from=builder /graph-node/target/release/graph-node /usr/local/bin/
EXPOSE 8020 8000 8001 8030 8040
CMD ["graph-node", \
    "--postgres-url", "postgresql://postgres:postgres@postgres:5432/graph-node", \
    "--ethereum-rpc", "base-sepolia:https://base-sepolia.gateway.tenderly.co/", \
    "--ethereum-rpc", "base:https://base.gateway.tenderly.co/", \
    "--ethereum-rpc", "opBNB-testnet:https://opbnb-testnet.g.alchemy.com/v2/vjS4hgV33RrHIi5pdkd1u", \
    "--ethereum-rpc", "opBNB:https://opbnb-mainnet.g.alchemy.com/v2/NJbEDHTkxxkRhJ6FALFOJ", \
    "--ipfs", "https://ipfs.network.thegraph.com/"]