# Dockerfile.graph-cli
FROM node:18-slim

RUN npm install -g @graphprotocol/graph-cli \
 && apt-get update \
 && apt-get install -y netcat-openbsd \
 && rm -rf /var/lib/apt/lists/*


WORKDIR /app


COPY . /app

RUN chmod +x /app/entrypoint.sh


ENTRYPOINT ["/app/entrypoint.sh"]
