const fs = require('fs')
const path = require('path')

const gatewayRoot = path.resolve(__dirname, '..')
const templatePath = path.join(gatewayRoot, 'subgraph.template.yaml')
const subgraphPath = path.join(gatewayRoot, 'subgraph.yaml')
const generatedAddressesPath = path.join(gatewayRoot, 'src', 'handlers', 'generatedLocalhostAddresses.ts')

const abiDirCandidates = [
  path.resolve(gatewayRoot, '..', '..', '..', 'RentalitySmartContracts', 'src', 'abis'),
  path.resolve(gatewayRoot, '..', '..', 'src', 'abis'),
]

function findAbiDir() {
  for (const candidate of abiDirCandidates) {
    if (fs.existsSync(candidate)) {
      return candidate
    }
  }

  throw new Error(`Unable to find ABI directory. Checked: ${abiDirCandidates.join(', ')}`)
}

function findAddressFile(fileName) {
  for (const abiDir of abiDirCandidates) {
    const filePath = path.join(abiDir, fileName)
    if (fs.existsSync(filePath)) {
      return filePath
    }
  }

  throw new Error(`Address file not found. Checked: ${abiDirCandidates.map((dir) => path.join(dir, fileName)).join(', ')}`)
}

function readLocalhostAddress(fileName) {
  const filePath = findAddressFile(fileName)

  const content = JSON.parse(fs.readFileSync(filePath, 'utf8'))
  const entry = content.addresses?.find((item) => Number(item.chainId) === 1337)

  if (!entry?.address) {
    throw new Error(`No localhost chainId 1337 address found in ${filePath}`)
  }

  return entry.address
}

function writeSubgraphYaml(notificationServiceAddress) {
  const template = fs.readFileSync(templatePath, 'utf8')
  const rendered = template.replace('{{RENTALITY_NOTIFICATION_SERVICE_ADDRESS}}', notificationServiceAddress)

  fs.writeFileSync(subgraphPath, rendered)
  console.log(`Updated subgraph manifest with RentalityNotificationService ${notificationServiceAddress}`)
}

function writeGeneratedAddresses(addresses) {
  const content = `// Auto-generated by scripts/syncLocalhostAddresses.js
export const RENTALITY_GATEWAY_ADDRESS = "${addresses.gateway}"
export const RENTALITY_TRIP_SERVICE_ADDRESS = "${addresses.tripQuery}"
export const RENTALITY_USER_SERVICE_ADDRESS = "${addresses.userProfileQuery}"
`

  fs.writeFileSync(generatedAddressesPath, content)
  console.log(`Updated generated localhost addresses in ${generatedAddressesPath}`)
}

function main() {
  findAbiDir()
  const addresses = {
    notificationService: readLocalhostAddress('RentalityNotificationService.v0_2_0.addresses.json'),
    gateway: readLocalhostAddress('RentalityGateway.v0_2_0.addresses.json'),
    tripQuery: readLocalhostAddress('TripQuery.v0_2_0.addresses.json'),
    userProfileQuery: readLocalhostAddress('UserProfileQuery.v0_2_0.addresses.json'),
  }

  writeSubgraphYaml(addresses.notificationService)
  writeGeneratedAddresses(addresses)
}

main()
