name: Build And Deploy to Demo Test

on:
  workflow_dispatch:   

permissions:
      id-token: write      
      contents: read
      
jobs:
  build_and_deploy_demo_test:
    runs-on: ubuntu-latest
    environment:
      name: Demo Test

    steps:
      - name: "Checkout main"
        uses: actions/checkout@v4
      
      - name: "Checkout Contracts Repo"
        uses: actions/checkout@v4
        with:
          repository: Rentality-xyz/Rentality-demo-contracts
          ref: "main"
          sparse-checkout: |
            contracts
            scripts
            src
          path: "demo-rentality-web3-contracts"
          # token: ${{ secrets.RENTALITY_PAT }}
          
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: "Generate environment"
        uses: SpicyPizza/create-envfile@v2.0
        with:
          fail_on_empty: true
          ENVKEY_DEBUG: false
          ENVKEY_FF_TRIP_PHOTOS: ${{ vars.FF_TRIP_PHOTOS }}
          ENVKEY_FF_INVESTMENTS: ${{ vars.FF_INVESTMENTS }}
          ENVKEY_NEXT_PUBLIC_DEFAULT_CHAIN_ID: ${{ vars.NEXT_PUBLIC_DEFAULT_CHAIN_ID }}
          ENVKEY_NEXT_PUBLIC_INCLUDE_LOCALNETS: ${{ vars.NEXT_PUBLIC_INCLUDE_LOCALNETS }}
          ENVKEY_NEXT_PUBLIC_INCLUDE_MAINNETS: ${{ vars.NEXT_PUBLIC_INCLUDE_MAINNETS }}
          ENVKEY_NEXT_PUBLIC_INCLUDE_TESTNETS: ${{ vars.NEXT_PUBLIC_INCLUDE_TESTNETS }}
          ENVKEY_NEXT_PUBLIC_SKIP_KYC_PAYMENT: ${{ vars.NEXT_PUBLIC_SKIP_KYC_PAYMENT }}
          ENVKEY_NEXT_PUBLIC_USE_ERUDA_DEV_TOOLS: ${{ vars.NEXT_PUBLIC_USE_ERUDA_DEV_TOOLS }}
          ENVKEY_CARAPI_SECRET: ${{ secrets.CARAPI_SECRET }}
          ENVKEY_CARAPI_TOKEN: ${{ secrets.CARAPI_TOKEN }}
          ENVKEY_CIVIC_CLIENT_ID: ${{ secrets.CIVIC_CLIENT_ID }}
          ENVKEY_CIVIC_CLIENT_SECRET: ${{ secrets.CIVIC_CLIENT_SECRET }}
          ENVKEY_NEXT_PUBLIC_USER_EMAIL: ${{ secrets.NEXT_PUBLIC_USER_EMAIL }}
          ENVKEY_NEXT_PUBLIC_USER_PASSWORD: ${{ secrets.NEXT_PUBLIC_USER_PASSWORD }}
          ENVKEY_PLATFORM_USER_EMAIL: ${{ secrets.PLATFORM_USER_EMAIL }}
          ENVKEY_PLATFORM_USER_PASSWORD: ${{ secrets.PLATFORM_USER_PASSWORD }}
          ENVKEY_MANAGER_PRIVATE_KEY: ${{ secrets.MANAGER_PRIVATE_KEY}}
          ENVKEY_ADMIN_VIEWER_PRIVATE_KEY: ${{ secrets.ADMIN_VIEWER_PRIVATE_KEY}}
          ENVKEY_NEXT_PUBLIC_CIVIC_GATEKEEPER_NETWORK: ${{ secrets.NEXT_PUBLIC_CIVIC_GATEKEEPER_NETWORK}}
          ENVKEY_NEXT_PUBLIC_COINBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_COINBASE_API_KEY }}
          ENVKEY_NEXT_PUBLIC_COINBASE_SCHEMA_ID: ${{ secrets.NEXT_PUBLIC_COINBASE_SCHEMA_ID }}
          ENVKEY_NEXT_PUBLIC_FB_PIXEL_ID: ${{ secrets.NEXT_PUBLIC_FB_PIXEL_ID }}
          ENVKEY_NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          ENVKEY_NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          ENVKEY_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          ENVKEY_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
          ENVKEY_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          ENVKEY_NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID}}
          ENVKEY_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          ENVKEY_NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}}
          ENVKEY_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY}}
          ENVKEY_NEXT_PUBLIC_HOTJAR_SITE_ID: ${{ secrets.NEXT_PUBLIC_HOTJAR_SITE_ID }}
          ENVKEY_NEXT_PUBLIC_HOTJAR_VERSION: ${{ secrets.NEXT_PUBLIC_HOTJAR_VERSION }}
          ENVKEY_NEXT_PUBLIC_PINATA_JWT: ${{ secrets.NEXT_PUBLIC_PINATA_JWT }}
          ENVKEY_NEXT_PUBLIC_PRIVY_APP_ID: ${{ secrets.NEXT_PUBLIC_PRIVY_APP_ID }}
          ENVKEY_PROVIDER_API_URL_11155111: ${{ secrets.PROVIDER_API_URL_11155111 }}
          ENVKEY_PROVIDER_API_URL_11155420: ${{ secrets.PROVIDER_API_URL_11155420 }}
          ENVKEY_PROVIDER_API_URL_1337: ${{ secrets.PROVIDER_API_URL_1337 }}
          ENVKEY_PROVIDER_API_URL_5611: ${{ secrets.PROVIDER_API_URL_5611}}
          ENVKEY_PROVIDER_API_URL_8453: ${{ secrets.PROVIDER_API_URL_8453}}
          ENVKEY_PROVIDER_API_URL_84532: ${{ secrets.PROVIDER_API_URL_84532 }}
          ENVKEY_SIGNER_PRIVATE_KEY: ${{ secrets.SIGNER_PRIVATE_KEY}}
          ENVKEY_TEST_WALLETS_ADDRESSES: ${{ secrets.TEST_WALLETS_ADDRESSES }}
          ENVKEY_NEXT_PUBLIC_SERVER_DIMO_DOMAIN: ${{ vars.NEXT_PUBLIC_SERVER_DIMO_DOMAIN }}
          ENVKEY_NEXT_PUBLIC_SERVER_DIMO_API_KEY: ${{ secrets.NEXT_PUBLIC_SERVER_DIMO_API_KEY }}
          ENVKEY_NEXT_PUBLIC_SERVER_DIMO_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_SERVER_DIMO_CLIENT_ID }}
          ENVKEY_PRIVY_VERIFICATION_KEY: ${{ secrets.PRIVY_VERIFICATION_KEY }}
          ENVKEY_NEXT_PUBLIC_IS_TECHNICAL_WORK: ${{ vars.NEXT_PUBLIC_IS_TECHNICAL_WORK }}
          ENVKEY_API_AI_DAMAGE_ANALYZE_SECRET: ${{ secrets.API_AI_DAMAGE_ANALYZE_SECRET }}
          ENVKEY_NEXT_PUBLIC_AI_DAMAGE_ANALYZE_BASE_URL: ${{ secrets.NEXT_PUBLIC_AI_DAMAGE_ANALYZE_BASE_URL }}
          ENVKEY_NEXT_PUBLIC_AI_DAMAGE_ANALYZE_ACCOUNT_SID: ${{ secrets.NEXT_PUBLIC_AI_DAMAGE_ANALYZE_ACCOUNT_SID }}
          ENVKEY_NEXT_PUBLIC_AI_DAMAGE_ANALYZE_ACCOUNT_SECRETKEY: ${{ secrets.NEXT_PUBLIC_AI_DAMAGE_ANALYZE_ACCOUNT_SECRETKEY }}
          ENVKEY_TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          ENVKEY_TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          ENVKEY_VERIFICATION_HMAC_SHA256_SECRET_KEY: ${{ secrets.VERIFICATION_HMAC_SHA256_SECRET_KEY }}
          ENVKEY_NOTIFICATION_SMTP_USER: ${{ secrets.NOTIFICATION_SMTP_USER }}
          ENVKEY_NOTIFICATION_SMTP_PASSWORD: ${{ secrets.NOTIFICATION_SMTP_PASSWORD }}
          ENVKEY_INDEXER_API_URL: ${{ secrets.INDEXER_API_URL }}
          ENVKEY_API_AUTH_TOKEN: ${{ secrets.API_AUTH_TOKEN }}
          ENVKEY_BASE_URL: ${{ vars.BASE_URL }}
          ENVKEY_FB_SERVICE_ACCOUNT: ${{ secrets.FB_SERVICE_ACCOUNT }}

      - name: "Build Rentality App"
        run: make build

      - name: "Remove Contracts Repo"
        run: rm -rf demo-rentality-web3-contracts

      - id: 'auth'
        name: 'Authenticate to Google Cloud via Workload Identity Federation'
        uses: 'google-github-actions/auth@v3'
        with:
            workload_identity_provider: 'projects/466243718843/locations/global/workloadIdentityPools/github-actions-pool-nextjs-test/providers/github-provider-nextjs-test'
            service_account: 'github-action-nextjs-test@rentality-demo-test.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      
      - name: "Fix for Firebase deployment"
        run: npm install -g firebase-tools firebase-frameworks
        
      - name: "Deploy to Firebase Hosting"
        run: firebase deploy #--only hosting --project rentality-demo-test
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
